# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6efcbbe601b986da8eac0a139b9bb6b840ae100e0b1454185a12013eb0bdd48c3ce361d5660c372a0eb031a646df71ad9e4bf320108070259136ca7a9864b9bf

test:
  secret_key_base: 259bc71db900c2280a49fed898e61ae8b9fb39a53aa22fc18be8ab6f163b665ca9c63dff87a806dff530e1ff5d82824165b4a09378400411332cdd7f7efc5e8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
